// lead-data.ts

export const LEAD_DATA = [
  {
    actions: 'Actions',
    recordId: 111994,
    lastName: 'TEST',
    firstName: 'APRILLELEVEN',
    email: 'TULSI.KULKARNI@WAIIN.COM',
    phoneType: 'Home (565) 656-5666-6',
    leadId: 2222000,
    appointmentType: '',
    bookingAgency: 2222000,
    status: 'Active',
    priority: 'High',
    createdDate: '2023-01-01',
    updatedDate: '2023-01-15',
    assignedTo: 'John Doe',
    department: 'Sales',
    region: 'North',
    comments: 'No comments',
  },
  {
    actions: 'Actions',
    recordId: 109907,
    lastName: 'Nat Storage',
    firstName: 'Marie',
    email: 'm@e.com',
    phoneType: 'Home (630) 555-2024',
    leadId: 2007000,
    appointmentType: '',
    bookingAgency: 2007000,
    status: 'Inactive',
    priority: 'Medium',
    createdDate: '2023-02-01',
    updatedDate: '2023-02-10',
    assignedTo: 'Jane Smith',
    department: 'Support',
    region: 'South',
    comments: 'Follow-up required',
  },
  {
    actions: 'Actions',
    recordId: 111962,
    lastName: 'Pathak 09-04',
    firstName: 'Pooja',
    email: 'p.u@gmail.com',
    phoneType: 'Home (313) 233-3233',
    leadId: 2222000,
    appointmentType: 'MS-Pro',
    bookingAgency: 2222000,
    status: 'Active',
    priority: 'Low',
    createdDate: '2023-03-01',
    updatedDate: '2023-03-05',
    assignedTo: 'Alice Johnson',
    department: 'Marketing',
    region: 'East',
    comments: 'Pending approval',
  },

  ...Array(32).fill({
    actions: 'Actions',
    recordId: 111999,
    lastName: 'Hello',
    firstName: 'User',
    email: 'sample.user@example.com',
    phoneType: 'Mobile (123) 456-7890',
    leadId: 123456,
    appointmentType: 'Standard',
    bookingAgency: 123456,
    status: 'Active',
    priority: 'High',
    createdDate: '2023-04-01',
    updatedDate: '2023-04-10',
    assignedTo: 'Default User',
    department: 'IT',
    region: 'West',
    comments: 'No comments',
  }),
  ...Array(30).fill({
    actions: 'Actions',
    recordId: 22222000,
    lastName: 'Last',
    firstName: 'User',
    email: 'Last.user@example.com',
    phoneType: 'Mobile (021) 123-9878',
    leadId: 123456,
    appointmentType: 'Low',
    bookingAgency: 789456,
    status: 'Not Active',
    priority: 'Very High',
    createdDate: '2020-12-01',
    updatedDate: '2025-04-10',
    assignedTo: 'Piyush User',
    department: 'IT',
    region: 'East',
    comments: 'Comments',
  }),
];
